### ISSUE TITLE
Idea: command line tools to set up new node services

### ISSUE THREAD

**Issue by Rush** [simone-sanfratello/service-systemd#4]
I like the overall idea of your project. What would be a perfect solution for me:

`node-service add my-service-name /home/rush/mywebapp bin/www`
- should add systemd service with name `my-service-name`
- command should be installable via `npm install -g node-service-systemd` as root
- where `/home/rush/mywebapp` is the working directory
- where `bin/www` is path to the node script relative to working directory
- should run it as user `rush` as he is the owner of working directory
- to remove `node-service remove my-service-name`

If it's not doable in the scope of yoru project I might give it a shot myself one day.

**Comment by simone-sanfratello** [comment]
Good idea, I will implement

**Comment by simone-sanfratello** [comment]
Done in v. 3.0
